"""empty message

Revision ID: 766cd45a7e64
Revises: 6697a3e9446e
Create Date: 2021-06-20 16:41:16.077293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766cd45a7e64'
down_revision = '6697a3e9446e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
